### PR TITLE
move to python 3.8+

### PR DESCRIPTION
**Pull request by danieleades**
sphinx 6.0 beta is out, and drops support for python <3.8.
sphinx-needs can follow suit (once the stable release is out)

### CODE REVIEW

**Comment by danwos** [comment]
I would like to close this PR, as it seems to outdated.
Any concerns?

**Comment by chrisjsewell** [comment]
> I would like to close this PR, as it seems to outdated. Any concerns?

@danwos to bump to new versions of sphinx, this would still be required. Python 3.7 is also end-of-life: https://devguide.python.org/versions/

What are your thoughts on bumping python/sphinx versions? Speaking with @ubmarco he suggested that we are less "aggressive" on bumping versions, since some businesses have to deal with older versions of Python?

**Comment by ubmarco** [comment]
We also have the [Compatibility with Sphinx 7.2](https://github.com/useblocks/sphinx-needs/pull/1045) PR now.
It contains new version constraints and remarks wrt API incompatibilities.

**Comment by chrisjsewell** [comment]
superceded by #1056

**Pull request closed without merging**
