### PR TITLE
latex output: Fix LaTeX output format for needs tables

### PR DESCRIPTION
**Pull request by tim-nordell-nimbelink**
This adds the `colwidths-given` class to the table generated with a simple needs table.  The LaTeX output then actually checks the <colspec> blocks for each column and respects the widths specified.

Additionally, the need table was originally generating a <line-block> context and populating it with <line> elements.  This ends up adding extra spacing into the output for whatever reason and took up a lot of vertical space for each need in the rendered LaTeX PDF output.  This has been removed and instead each line is placed into a new paragraph context via nodes.paragraph().  This renders the output correctly, and the HTML side is captured via CSS to ensure that there are no margins around the paragraph.

Other attempts to solve the rendering didn't work.  If I moved the class into a nodes.inline(...) element, the LaTeX renderer doesn't like having a nested paragraph inside of a class defined via `inline(...)`.  Placing a pair of newlines, defining a new paragraph that way, also yielded the same error from the LaTeX renderer.  (I also tried using `nodes.container(...)` in lieu of `nodes.inline(...)`, but this added an extra trailing line in each section of the simple table.)

Note: Currently this breaks some of the test cases, and I haven't investigated these.  (I was more interested in figuring out how to fix the LaTeX output.)

Potentially fixes https://github.com/useblocks/sphinx-needs/issues/278.

### CODE REVIEW

**Comment by danwos** [comment]
Only 4 failing tests and the Sphinx-Needs documentation looks good.
Also our JS code for the collapse button still works.

So I would say this PR looks really promising.

Are you also able to fix the test case or do you need some support here?

For a final PR, we also need an entry in the ``docs/changelog.rst`` file, and for sure, feel free to add yourself to the ``AUTHORS`` file.

Thanks for your help :+1: 
LaTeX skills are also welcome, as it was not the favored builder in the past.

**Comment by tim-nordell-nimbelink** [comment]
I did some further testing, and it breaks some of the custom layout stuff.  Specifically, multiple lines within the custom layouts are broken since I took out the outer-most `nodes.line()` that was getting created.

The LaTeX output can also recognize two newlines in a row in the text output as a paragraph.  When testing with this, the last double newline ends up creating an extra line on the last line within a given section.  I think what should ultimately happen is all individual lines should end up in a single, non-nested, `nodes.container()`, and then insert the double newlines.  This would yield a `<div>` element in HTML, and the appropriate new paragraph.  Alternatively, each could end up in a single `nodes.paragraph()` element.  The `nodes.container()` allows for nested inline classes, though, which is more ideal for the HTML side of things.  The `nodes.paragraph()` does not allow nested inline classes.

I'll leave this additional refactoring for a future patch.

**Comment by danwos** [comment]
I would like to close this PR, as it seems outdated and nobody was working on it.

Especially the current implementation changes some HTML code and breaks some stuff.
As PDF-Alternative there is also[ Sphinx-SimplePDF](https://sphinx-simplepdf.readthedocs.io/en/latest/), which works quite well with Sphinx-Needs as it is using an HTML build for the PDF generation.

**Comment by tim-nordell-nimbelink** [comment]
@danwos -

Sure, we can close this.

- Tim

**Pull request closed without merging**
