### PR TITLE
removed leading space in ref function in needuml.py

### PR DESCRIPTION
**Pull request by PhilipPartsch**
Try to solve #1204

### CODE REVIEW

**Comment by PhilipPartsch** [comment]
@danwos and @chrisjsewell: I cannot fix the issues by myself, can you help me.
1. Issue: Some jobs are failing, as it is not possible to upload the coverage report to https://codecov.io :
```
There was an error running the uploader: Error uploading to [https://codecov.io:](https://codecov.io/) Error: There was an error fetching the storage URL during POST: 429 - {'detail': ErrorDetail(string='Rate limit reached. Please upload with the Codecov repository upload token to resolve issue. Expected time to availability: 1492s.', code='throttled')}
```

2. In Sphinx 7 is a change in the project configuration. See [build job](https://github.com/useblocks/sphinx-needs/actions/runs/9988800411/job/27606064803?pr=1205). Does you know how to fix it?

**Comment by chrisjsewell** [comment]
Heya @PhilipPartsch fyi daniel is away on holiday for the next few weeks. I probably won't have time to look at it this week, but hopefully next

**Comment by danwos** [comment]
Hi guys,
I have created #1209 for the CI problem.

**Review by danwos — APPROVED** [review]
Thanks for the PR.
Finally our CI got fixed.

**Pull request merged**
