### PR TITLE
🧪 CI: Fail on sphinx-build warnings

### PR DESCRIPTION
**Pull request by chrisjsewell**
Thanks for #972 @danwos, now I can actually build the docs 😅 

However, I noticed that there were still lots of warnings occuring, e.g. plantuml errors (is this what #973 is intending to fix?)

This change to the CI, should make these warnings fail the job (then obviously we need to fix those warnings)

See also  #975

### CODE REVIEW

**Comment by danwos** [comment]
Thanks for the PR, I'm waring with a merge till we fixed all the stuff first, otherwise it will block our CI.

And somehow yes, #973 got created, because I had problems identifying the root cause of PlantUML errors, as the exact location was not printed. And because other user have also asked for it, I created a not-so-clean, but doable fix.

**Comment by danwos** [comment]
For PlantUML errors, notice also #977, which describes problems in `needgantt`

**Comment by chrisjsewell** [comment]
> I'm waring with a merge till we fixed all the stuff first, otherwise it will block our CI.

Oh indeed, thats why it marked as a draft 😄

**Comment by chrisjsewell** [comment]
From #982, these are the actual origin of the remaining warnings:

```
/Users/chrisjsewell/Documents/GitHub/sphinx-needs/docs/directives/needgantt.rst:20: WARNING: error while running plantuml

b'ERROR\n4\nSyntax Error?\nSome diagram description contains errors\n'
/Users/chrisjsewell/Documents/GitHub/sphinx-needs/docs/directives/needgantt.rst:134: WARNING: error while running plantuml

b'ERROR\n4\nSyntax Error?\nSome diagram description contains errors\n'
/Users/chrisjsewell/Documents/GitHub/sphinx-needs/docs/directives/needgantt.rst:176: WARNING: error while running plantuml

b'ERROR\n4\nSyntax Error?\nSome diagram description contains errors\n'
/Users/chrisjsewell/Documents/GitHub/sphinx-needs/docs/directives/needgantt.rst:212: WARNING: error while running plantuml

b'ERROR\n4\nSyntax Error?\nSome diagram description contains errors\n'
/Users/chrisjsewell/Documents/GitHub/sphinx-needs/docs/directives/needgantt.rst:250: WARNING: error while running plantuml

b'ERROR\n1\nSyntax Error?\nSome diagram description contains errors\n'
/Users/chrisjsewell/Documents/GitHub/sphinx-needs/docs/directives/needgantt.rst:281: WARNING: error while running plantuml

b'ERROR\n1\nSyntax Error?\nSome diagram description contains errors\n'
/Users/chrisjsewell/Documents/GitHub/sphinx-needs/docs/directives/needgantt.rst:295: WARNING: error while running plantuml

b'ERROR\n4\nSyntax Error?\nSome diagram description contains errors\n'
/Users/chrisjsewell/Documents/GitHub/sphinx-needs/docs/directives/needgantt.rst:322: WARNING: error while running plantuml

b'ERROR\n4\nSyntax Error?\nSome diagram description contains errors\n'
/Users/chrisjsewell/Documents/GitHub/sphinx-needs/docs/directives/needgantt.rst:366: WARNING: error while running plantuml

b'ERROR\n4\nSyntax Error?\nSome diagram description contains errors\n'
/Users/chrisjsewell/Documents/GitHub/sphinx-needs/docs/dynamic_functions.rst:63: WARNING: Filter current_need["sections"][-1]==sections[-1] not valid. Error: name 'sections' is not defined. [needs]
WARNING: Filter "Referencing and filtering needs" == section_name not valid. Error: name 'section_name' is not defined. [needs]
```

**Comment by chrisjsewell** [comment]
superceded by #1005

**Pull request closed without merging**
