### PR TITLE
[877] fix master_doc is not index

### PR DESCRIPTION
**Pull request by kreuzberger**
Hardcoded `master_doc` or `root_doc` config value replaced with config value from app environment

### CODE REVIEW

**Comment by danwos** [comment]
Thanks @kreuzberger for the PR. :+1: 
It looks good and fixes a really dumb mistake, made by myself.

It will get merged, but two steps are missing:
1) Green status for CI / Lint test. You can check this also locally by ``make lint``.
2) Add a short line to the `docs/changelog.rst` file.

**Comment by kreuzberger** [comment]
Will made the required changes. Thought we get a discussion on the tests name first :smile:

**Comment by danwos** [comment]
> Will made the required changes. Thought we get a discussion on the tests name first smile

I'm ok with the names. It's just a test and as long as the test itself makes sense, the PR is fine :)

**Comment by kreuzberger** [comment]
lokal linting is not possible for me cause the pre-commit script is not available. I tried with poerty run [black, isort, flake8].
Seems to b a litte different (changes more files than just the files i modified)
But committing only my files

**Review by danwos — APPROVED** [review]
Looks good, thanks for the changes.

**Pull request merged**
